services:
  letter:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - USER=${USER}
    user: "${UID}:${GID}"
    volumes:
      - ./:${HOME}/loveletter
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    tty: true
    working_dir: ${HOME}/loveletter
